language: python
sudo: false
python:
  - "2.7"
install:
  - python setup.py install
  - python setup.py develop
script:
  - python setup.py test
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/0497795e975cf2d6f93e
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
os:
  - linux
  - osx
